
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Apr  5 2025 14:59:31 IST (Apr  5 2025 09:29:31 UTC)

// Verification Directory fv/top_module 

module NEGDFF_166(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_165(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_164(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_163(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_162(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_161(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_160(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_159(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module POSDLATCH_236(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LHQD1 Q_reg(.E (CLK), .D (D), .Q (Q));
endmodule

module MUX(in1, in2, sel, out);
  input in1, in2, sel;
  output out;
  wire in1, in2, sel;
  wire out;
  MUX2D0 g27__2398(.I0 (in1), .I1 (in2), .S (sel), .Z (out));
endmodule

module XOR_321(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__5107(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_320(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__6260(.A1 (a), .A2 (b), .Z (x));
endmodule

module XOR_319(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__4319(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_318(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__8428(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_317(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__5526(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_316(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__6783(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_315(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__3680(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_314(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__1617(.A1 (a), .A2 (b), .Z (x));
endmodule

module XOR_313(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__2802(.A1 (a), .A2 (b), .Z (x));
endmodule

module CRBS(clk, selmux, OUT1, OUT2, OUT3, OUT4);
  input clk, selmux;
  output OUT1, OUT2, OUT3, OUT4;
  wire clk, selmux;
  wire OUT1, OUT2, OUT3, OUT4;
  wire [8:1] D;
  wire [8:1] Q;
  wire [9:1] X;
  wire [4:1] QL;
  NEGDFF_166 dff1(Q[1], D[1], clk);
  NEGDFF_165 dff2(Q[2], X[2], clk);
  NEGDFF_164 dff3(Q[3], X[3], clk);
  NEGDFF_163 dff4(Q[4], X[4], clk);
  NEGDFF_162 dff5(Q[5], X[5], clk);
  NEGDFF_161 dff6(Q[6], X[6], clk);
  NEGDFF_160 dff7(Q[7], X[7], clk);
  NEGDFF_159 dff8(Q[8], X[8], clk);
  POSDLATCH_236 dlatch4(QL[4], Q[8], clk);
  MUX mux4(Q[4], QL[4], clk, OUT4);
  XOR_321 xor1(X[1], Q[7], X[7]);
  XOR_320 xor2(X[2], X[9], X[8]);
  XOR_319 xor3(X[3], Q[2], X[6]);
  XOR_318 xor4(X[4], Q[3], X[7]);
  XOR_317 xor5(X[5], Q[4], X[8]);
  XOR_316 xor6(X[6], Q[5], Q[1]);
  XOR_315 xor7(X[7], Q[6], Q[2]);
  XOR_314 xor8(X[8], Q[7], Q[3]);
  XOR_313 xor9(X[9], Q[1], Q[4]);
  OR2D1 g5__1705(.A1 (selmux), .A2 (X[1]), .Z (D[1]));
endmodule

module NEGDFF_158(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_157(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_156(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_155(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_154(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_153(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_152(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_151(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_150(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module POSDLATCH_235(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LHQD1 Q_reg(.E (CLK), .D (D), .Q (Q));
endmodule

module MUX_9(in1, in2, sel, out);
  input in1, in2, sel;
  output out;
  wire in1, in2, sel;
  wire out;
  MUX2D0 g27__5122(.I0 (in1), .I1 (in2), .S (sel), .Z (out));
endmodule

module XOR_312(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__8246(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_311(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__7098(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_310(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__6131(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_309(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__1881(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_308(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__5115(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_307(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__7482(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_306(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__4733(.A1 (a), .A2 (b), .Z (x));
endmodule

module XOR_305(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__6161(.A1 (a), .A2 (b), .Z (x));
endmodule

module CRBS_9(clk, selmux, OUT1, OUT2, OUT3, OUT4);
  input clk, selmux;
  output OUT1, OUT2, OUT3, OUT4;
  wire clk, selmux;
  wire OUT1, OUT2, OUT3, OUT4;
  wire [9:1] D;
  wire [9:1] Q;
  wire [8:1] X;
  wire [4:1] QL;
  NEGDFF_158 dff1(Q[1], D[1], clk);
  NEGDFF_157 dff2(Q[2], X[2], clk);
  NEGDFF_156 dff3(Q[3], X[3], clk);
  NEGDFF_155 dff4(Q[4], X[4], clk);
  NEGDFF_154 dff5(Q[5], X[5], clk);
  NEGDFF_153 dff6(Q[6], X[6], clk);
  NEGDFF_152 dff7(Q[7], X[7], clk);
  NEGDFF_151 dff8(Q[8], X[8], clk);
  NEGDFF_150 dff9(Q[9], Q[1], clk);
  POSDLATCH_235 dlatch4(QL[4], Q[8], clk);
  MUX_9 mux4(Q[4], QL[4], clk, OUT4);
  XOR_312 xor1(X[1], Q[2], X[5]);
  XOR_311 xor2(X[2], X[6], Q[3]);
  XOR_310 xor3(X[3], Q[4], X[7]);
  XOR_309 xor4(X[4], Q[5], X[8]);
  XOR_308 xor5(X[5], Q[6], Q[1]);
  XOR_307 xor6(X[6], Q[7], Q[2]);
  XOR_306 xor7(X[7], Q[8], Q[3]);
  XOR_305 xor8(X[8], Q[4], Q[9]);
  OR2D1 g5__9315(.A1 (X[1]), .A2 (selmux), .Z (D[1]));
endmodule

module NEGDFF_149(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_148(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_147(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_146(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_145(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_144(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_143(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_142(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_141(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_140(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_139(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_138(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_137(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_136(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_135(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module POSDLATCH_234(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LHQD1 Q_reg(.E (CLK), .D (D), .Q (Q));
endmodule

module MUX_8(in1, in2, sel, out);
  input in1, in2, sel;
  output out;
  wire in1, in2, sel;
  wire out;
  MUX2D0 g27__9945(.I0 (in1), .I1 (in2), .S (sel), .Z (out));
endmodule

module XOR_304(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__2883(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_303(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__2346(.A1 (a), .A2 (b), .Z (x));
endmodule

module XOR_302(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__1666(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_301(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__7410(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_300(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__6417(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_299(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__5477(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_298(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__2398(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_297(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__5107(.A1 (a), .A2 (b), .Z (x));
endmodule

module CRBS_15(clk, selmux, OUT1, OUT2, OUT3, OUT4);
  input clk, selmux;
  output OUT1, OUT2, OUT3, OUT4;
  wire clk, selmux;
  wire OUT1, OUT2, OUT3, OUT4;
  wire [15:1] D;
  wire [15:1] Q;
  wire [8:1] X;
  wire [4:1] QL;
  NEGDFF_149 dff1(Q[1], D[1], clk);
  NEGDFF_148 dff2(Q[2], X[2], clk);
  NEGDFF_147 dff3(Q[3], X[3], clk);
  NEGDFF_146 dff4(Q[4], X[4], clk);
  NEGDFF_145 dff5(Q[5], X[5], clk);
  NEGDFF_144 dff6(Q[6], X[6], clk);
  NEGDFF_143 dff7(Q[7], X[7], clk);
  NEGDFF_142 dff8(Q[8], X[8], clk);
  NEGDFF_141 dff9(Q[9], Q[1], clk);
  NEGDFF_140 dff10(Q[10], Q[2], clk);
  NEGDFF_139 dff11(Q[11], Q[3], clk);
  NEGDFF_138 dff12(Q[12], Q[4], clk);
  NEGDFF_137 dff13(Q[13], Q[5], clk);
  NEGDFF_136 dff14(Q[14], Q[6], clk);
  NEGDFF_135 dff15(Q[15], Q[7], clk);
  POSDLATCH_234 dlatch4(QL[4], Q[8], clk);
  MUX_8 mux4(Q[12], QL[4], clk, OUT4);
  XOR_304 xor1(X[1], Q[8], X[8]);
  XOR_303 xor2(X[2], Q[1], Q[9]);
  XOR_302 xor3(X[3], Q[2], Q[10]);
  XOR_301 xor4(X[4], Q[3], Q[11]);
  XOR_300 xor5(X[5], Q[4], Q[12]);
  XOR_299 xor6(X[6], Q[5], Q[13]);
  XOR_298 xor7(X[7], Q[6], Q[14]);
  XOR_297 xor8(X[8], Q[7], Q[15]);
  OR2D1 g5__6260(.A1 (selmux), .A2 (X[1]), .Z (D[1]));
endmodule

module NEGDFF_170(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_169(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
endmodule

module POSDFF_214(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LNQD1 Q1_reg(.EN (CLK), .D (D), .Q (Q1));
  LHQD1 Q2_reg(.E (CLK), .D (Q1), .Q (Q2));
endmodule

module POSDFF_213(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q2_reg(.E (CLK), .D (Q1), .Q (Q2));
  LNQD1 Q1_reg(.EN (CLK), .D (D), .Q (Q1));
endmodule

module NEGDFF_168(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_167(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
endmodule

module POSDFF_212(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LNQD1 Q1_reg(.EN (CLK), .D (D), .Q (Q1));
  LHQD1 Q2_reg(.E (CLK), .D (Q1), .Q (Q2));
endmodule

module POSDFF_211(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q2_reg(.E (CLK), .D (Q1), .Q (Q2));
  LNQD1 Q1_reg(.EN (CLK), .D (D), .Q (Q1));
endmodule

module POSDLATCH_243(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LHQD1 Q_reg(.E (CLK), .D (D), .Q (Q));
endmodule

module NEGDLATCH_196(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LNQD1 Q_reg(.EN (CLK), .D (D), .Q (Q));
endmodule

module POSDLATCH_242(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LHQD1 Q_reg(.E (CLK), .D (D), .Q (Q));
endmodule

module NEGDLATCH_195(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LNQD1 Q_reg(.EN (CLK), .D (D), .Q (Q));
endmodule

module POSDLATCH_241(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LHQD1 Q_reg(.E (CLK), .D (D), .Q (Q));
endmodule

module NEGDLATCH_194(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LNQD1 Q_reg(.EN (CLK), .D (D), .Q (Q));
endmodule

module NEGDLATCH_193(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LNQD1 Q_reg(.EN (CLK), .D (D), .Q (Q));
endmodule

module POSDLATCH_240(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LHQD1 Q_reg(.E (CLK), .D (D), .Q (Q));
endmodule

module POSDLATCH_239(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LHQD1 Q_reg(.E (CLK), .D (D), .Q (Q));
endmodule

module NEGDLATCH_192(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LNQD1 Q_reg(.EN (CLK), .D (D), .Q (Q));
endmodule

module POSDLATCH_237(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LHQD1 Q_reg(.E (CLK), .D (D), .Q (Q));
endmodule

module NEGDLATCH_191(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LNQD1 Q_reg(.EN (CLK), .D (D), .Q (Q));
endmodule

module POSDLATCH_238(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LHQD1 Q_reg(.E (CLK), .D (D), .Q (Q));
endmodule

module NEGDLATCH_190(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LNQD1 Q_reg(.EN (CLK), .D (D), .Q (Q));
endmodule

module OR_209(a, b, y);
  input a, b;
  output y;
  wire a, b;
  wire y;
  OR2D1 g2__4319(.A1 (b), .A2 (a), .Z (y));
endmodule

module XOR_328(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  wire n_0;
  MOAI22D1 g13__8428(.A1 (a), .A2 (n_0), .B1 (a), .B2 (n_0), .ZN (x));
  INVD1 g14(.I (b), .ZN (n_0));
endmodule

module XOR_327(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  wire n_0, n_1, n_2;
  IOA21D1 g13__5526(.A1 (n_0), .A2 (a), .B (n_2), .ZN (x));
  CKND2D1 g14__6783(.A1 (b), .A2 (n_1), .ZN (n_2));
  INVD1 g15(.I (a), .ZN (n_1));
  CKND1 g16(.I (b), .ZN (n_0));
endmodule

module XOR_326(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  wire n_0, n_1, n_2;
  ND2D1 g13__3680(.A1 (n_2), .A2 (n_0), .ZN (x));
  ND2D1 g15__1617(.A1 (n_1), .A2 (a), .ZN (n_2));
  CKND1 fopt(.I (b), .ZN (n_1));
  IND2D1 g2__2802(.A1 (a), .B1 (b), .ZN (n_0));
endmodule

module XOR_325(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  wire n_0;
  MOAI22D1 g13__1705(.A1 (a), .A2 (n_0), .B1 (a), .B2 (n_0), .ZN (x));
  INVD1 g14(.I (b), .ZN (n_0));
endmodule

module XOR_324(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  XOR2D0 g13__5122(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_323(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  wire n_0, n_1, n_3;
  IOA21D1 g13__8246(.A1 (b), .A2 (n_1), .B (n_3), .ZN (x));
  ND2D1 g14__7098(.A1 (a), .A2 (n_0), .ZN (n_3));
  CKND1 g16(.I (a), .ZN (n_1));
  INVD1 g17(.I (b), .ZN (n_0));
endmodule

module XOR_322(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  XOR2D0 g13__6131(.A1 (b), .A2 (a), .Z (x));
endmodule

module PRBS_7_9_15(clk, S1, S2, S3, SELMUX, OUT1, OUT2, OUT3, OUT4);
  input clk, S1, S2, S3, SELMUX;
  output OUT1, OUT2, OUT3, OUT4;
  wire clk, S1, S2, S3, SELMUX;
  wire OUT1, OUT2, OUT3, OUT4;
  wire [8:1] D;
  wire [8:1] Q;
  wire [14:1] QL;
  wire [14:1] DL;
  wire [7:1] A;
  wire [7:1] B;
  wire \DL[2]_8 , \DL[6]_9 , \DL[10]_10 , \DL[13]_11 , D_wire, n_0,
       n_1, n_2;
  wire n_3, y1, y2, y3;
  NEGDFF_170 dff1(Q[1], D[1], clk);
  NEGDFF_169 dff3(Q[2], D_wire, clk);
  POSDFF_214 dff5(Q[3], D[1], clk);
  POSDFF_213 dff7(Q[4], QL[6], clk);
  NEGDFF_168 dff9(Q[5], D[5], clk);
  NEGDFF_167 dff11(Q[6], QL[10], clk);
  POSDFF_212 dff12(Q[7], D[5], clk);
  POSDFF_211 dff14(Q[8], QL[13], clk);
  POSDLATCH_243 dff21(QL[1], DL[1], clk);
  NEGDLATCH_196 dff22(QL[2], \DL[2]_8 , clk);
  POSDLATCH_242 dff41(QL[3], A[5], clk);
  NEGDLATCH_195 dff42(QL[4], QL[3], clk);
  POSDLATCH_241 dff61(QL[5], DL[5], clk);
  NEGDLATCH_194 dff62(QL[6], \DL[6]_9 , clk);
  NEGDLATCH_193 dff81(QL[7], B[5], clk);
  POSDLATCH_240 dff82(QL[8], QL[7], clk);
  POSDLATCH_239 dff101(QL[9], DL[9], clk);
  NEGDLATCH_192 dff102(QL[10], \DL[10]_10 , clk);
  POSDLATCH_237 dff131(QL[12], DL[12], clk);
  NEGDLATCH_191 dff132(QL[13], \DL[13]_11 , clk);
  POSDLATCH_238 dlatch1(QL[11], A[7], clk);
  NEGDLATCH_190 dlatch2(QL[14], B[7], clk);
  OR_209 or1(SELMUX, QL[2], D_wire);
  XOR_328 xor1(y1, QL[4], QL[8]);
  XOR_327 xor2(y2, QL[3], QL[7]);
  XOR_326 xor3(y3, QL[11], QL[14]);
  XOR_325 xor4(OUT1, y3, OUT4);
  XOR_324 xor5(OUT2, A[5], B[5]);
  XOR_323 xor6(OUT3, y1, y2);
  XOR_322 xor7(OUT4, A[7], B[7]);
  LHQD1 \DL_reg[3]16 (.E (S3), .D (Q[2]), .Q (A[5]));
  LHQD1 \DL_reg[7]17 (.E (S3), .D (Q[4]), .Q (B[5]));
  LHQD1 \DL_reg[11]18 (.E (S3), .D (Q[6]), .Q (A[7]));
  IOA21D0 g160__1881(.A1 (n_1), .A2 (QL[1]), .B (n_3), .ZN (\DL[2]_8 ));
  IOA21D1 g161__5115(.A1 (n_1), .A2 (QL[12]), .B (n_2), .ZN (\DL[13]_11
       ));
  IOA21D1 g163__7482(.A1 (n_1), .A2 (QL[9]), .B (n_2), .ZN (\DL[10]_10
       ));
  IND2D1 g164__4733(.A1 (n_1), .B1 (OUT1), .ZN (n_3));
  ND2D1 g165__6161(.A1 (S2), .A2 (OUT3), .ZN (n_2));
  INVD1 g166(.I (S2), .ZN (n_1));
  IND2D1 g5__9315(.A1 (n_0), .B1 (n_3), .ZN (\DL[6]_9 ));
  AN2XD1 g6__9945(.A1 (n_1), .A2 (QL[5]), .Z (n_0));
  LHQD1 \DL_reg[14]19 (.E (S3), .D (Q[8]), .Q (B[7]));
  LNQD1 \D_reg[1] (.EN (S2), .D (OUT1), .Q (D[1]));
  LNQD1 \D_reg[5] (.EN (S2), .D (OUT3), .Q (D[5]));
  LNQD1 \DL_reg[7] (.EN (S1), .D (Q[3]), .Q (B[5]));
  LNQD1 \DL_reg[3] (.EN (S1), .D (Q[1]), .Q (A[5]));
  LHQD1 \DL_reg[1] (.E (S1), .D (Q[1]), .Q (DL[1]));
  LNQD1 \DL_reg[14] (.EN (S1), .D (Q[7]), .Q (B[7]));
  LNQD1 \DL_reg[11] (.EN (S1), .D (Q[5]), .Q (A[7]));
  LHQD1 \DL_reg[5] (.E (S1), .D (Q[3]), .Q (DL[5]));
  LHQD1 \DL_reg[9] (.E (S1), .D (Q[5]), .Q (DL[9]));
  LHQD1 \DL_reg[12] (.E (S1), .D (Q[7]), .Q (DL[12]));
endmodule

module OR_210(a, b, y);
  input a, b;
  output y;
  wire a, b;
  wire y;
  OR2D1 g2__2883(.A1 (a), .A2 (b), .Z (y));
endmodule

module OR(a, b, y);
  input a, b;
  output y;
  wire a, b;
  wire y;
  OR2D1 g2__2346(.A1 (a), .A2 (b), .Z (y));
endmodule

module POSDFF_224(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q2_reg(.E (CLK), .D (Q1), .Q (Q2));
  LNQD1 Q1_reg(.EN (CLK), .D (D), .Q (Q1));
endmodule

module NEGDFF_180(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module POSDFF_223(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q2_reg(.E (CLK), .D (Q1), .Q (Q2));
  LNQD1 Q1_reg(.EN (CLK), .D (D), .Q (Q1));
endmodule

module NEGDFF_179(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
endmodule

module POSDFF_222(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LNQD1 Q1_reg(.EN (CLK), .D (D), .Q (Q1));
  LHQD1 Q2_reg(.E (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_178(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
endmodule

module POSDFF_221(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q2_reg(.E (CLK), .D (Q1), .Q (Q2));
  LNQD1 Q1_reg(.EN (CLK), .D (D), .Q (Q1));
endmodule

module NEGDFF_177(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module POSDFF_220(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q2_reg(.E (CLK), .D (Q1), .Q (Q2));
  LNQD1 Q1_reg(.EN (CLK), .D (D), .Q (Q1));
endmodule

module NEGDFF_176(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module POSDFF_219(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q2_reg(.E (CLK), .D (Q1), .Q (Q2));
  LNQD1 Q1_reg(.EN (CLK), .D (D), .Q (Q1));
endmodule

module NEGDFF_175(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module POSDFF_218(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LNQD1 Q1_reg(.EN (CLK), .D (D), .Q (Q1));
  LHQD1 Q2_reg(.E (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_174(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module POSDFF_217(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q2_reg(.E (CLK), .D (Q1), .Q (Q2));
  LNQD1 Q1_reg(.EN (CLK), .D (D), .Q (Q1));
endmodule

module NEGDFF_173(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module POSDFF_216(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q2_reg(.E (CLK), .D (Q1), .Q (Q2));
  LNQD1 Q1_reg(.EN (CLK), .D (D), .Q (Q1));
endmodule

module NEGDFF_172(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module POSDFF_215(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q2_reg(.E (CLK), .D (Q1), .Q (Q2));
  LNQD1 Q1_reg(.EN (CLK), .D (D), .Q (Q1));
endmodule

module NEGDFF_171(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDLATCH_198(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LNQD1 Q_reg(.EN (CLK), .D (D), .Q (Q));
endmodule

module POSDLATCH_245(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LHQD1 Q_reg(.E (CLK), .D (D), .Q (Q));
endmodule

module POSDLATCH_244(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LHQD1 Q_reg(.E (CLK), .D (D), .Q (Q));
endmodule

module NEGDLATCH_197(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LNQD1 Q_reg(.EN (CLK), .D (D), .Q (Q));
endmodule

module XOR_333(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__1666(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_332(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__7410(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_331(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__6417(.A1 (a), .A2 (b), .Z (x));
endmodule

module XOR_330(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__5477(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_329(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__2398(.A1 (a), .A2 (b), .Z (x));
endmodule

module PRBS_7_15_22(clk, S1, S2, SEL, OUT1, OUT2, OUT3, OUT4);
  input clk, S1, S2, SEL;
  output OUT1, OUT2, OUT3, OUT4;
  wire clk, S1, S2, SEL;
  wire OUT1, OUT2, OUT3, OUT4;
  wire [20:1] Q;
  wire [20:1] D;
  wire [4:1] QL;
  wire [4:1] DL;
  wire [3:1] FD;
  wire \D[13]_8 , O2, O4, n_0, n_1, n_2, n_3, n_4;
  OR_210 I49(SEL, Q[6], O4);
  OR I50(SEL, Q[5], O2);
  POSDFF_224 dff1(Q[1], Q[3], clk);
  NEGDFF_180 dff2(Q[2], Q[4], clk);
  POSDFF_223 dff3(Q[3], O2, clk);
  NEGDFF_179 dff4(Q[4], O4, clk);
  POSDFF_222 dff5(Q[5], D[4], clk);
  NEGDFF_178 dff6(Q[6], D[6], clk);
  POSDFF_221 dff7(D[5], Q[9], clk);
  NEGDFF_177 dff8(Q[8], Q[10], clk);
  POSDFF_220 dff9(Q[9], Q[11], clk);
  NEGDFF_176 dff10(Q[10], Q[12], clk);
  POSDFF_219 dff11(Q[11], Q[13], clk);
  NEGDFF_175 dff12(Q[12], Q[14], clk);
  POSDFF_218 dff13(Q[13], \D[13]_8 , clk);
  NEGDFF_174 dff14(Q[14], D[14], clk);
  POSDFF_217 dff15(D[13], Q[17], clk);
  NEGDFF_173 dff16(Q[16], Q[18], clk);
  POSDFF_216 dff17(Q[17], Q[19], clk);
  NEGDFF_172 dff18(Q[18], Q[20], clk);
  POSDFF_215 dff19(Q[19], QL[3], clk);
  NEGDFF_171 dff20(Q[20], QL[4], clk);
  NEGDLATCH_198 dlatch1(QL[1], Q[1], clk);
  POSDLATCH_245 dlatch2(QL[2], Q[2], clk);
  POSDLATCH_244 dlatch3(QL[3], DL[3], clk);
  NEGDLATCH_197 dlatch4(QL[4], DL[3], clk);
  XOR_333 xor1(OUT1, Q[1], Q[2]);
  XOR_332 xor2(OUT2, Q[3], Q[4]);
  XOR_331 xor3(OUT3, Q[5], Q[6]);
  XOR_330 xor4(OUT4, D[5], Q[8]);
  XOR_329 xor11(FD[2], QL[1], QL[2]);
  OAI21D1 g195__5107(.A1 (S2), .A2 (n_1), .B (n_4), .ZN (\D[13]_8 ));
  OAI21D1 g196__6260(.A1 (S2), .A2 (n_2), .B (n_4), .ZN (D[14]));
  IOA21D1 g197__4319(.A1 (n_0), .A2 (Q[8]), .B (n_3), .ZN (D[6]));
  OAI21D1 g198__8428(.A1 (S1), .A2 (FD[2]), .B (S2), .ZN (n_4));
  OR3D1 g199__5526(.A1 (FD[2]), .A2 (S2), .A3 (S1), .Z (DL[3]));
  IOA21D1 g200__6783(.A1 (n_0), .A2 (D[5]), .B (n_3), .ZN (D[4]));
  ND2D1 g201__3680(.A1 (S1), .A2 (FD[2]), .ZN (n_3));
  INVD1 g202(.I (Q[16]), .ZN (n_2));
  INVD1 g203(.I (D[13]), .ZN (n_1));
  CKND1 g204(.I (S1), .ZN (n_0));
endmodule

module NEGDFF(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
endmodule

module POSDFF(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LNQD1 Q1_reg(.EN (CLK), .D (D), .Q (Q1));
  LHQD1 Q2_reg(.E (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_189(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module POSDFF_233(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LNQD1 Q1_reg(.EN (CLK), .D (D), .Q (Q1));
  LHQD1 Q2_reg(.E (CLK), .D (Q1), .Q (Q2));
endmodule

module POSDLATCH(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LHQD1 Q_reg(.E (CLK), .D (D), .Q (Q));
endmodule

module NEGDLATCH(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LNQD1 Q_reg(.EN (CLK), .D (D), .Q (Q));
endmodule

module POSDLATCH_255(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LHQD1 Q_reg(.E (CLK), .D (D), .Q (Q));
endmodule

module NEGDLATCH_208(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LNQD1 Q_reg(.EN (CLK), .D (D), .Q (Q));
endmodule

module NEGDLATCH_207(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LNQD1 Q_reg(.EN (CLK), .D (D), .Q (Q));
endmodule

module POSDLATCH_254(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LHQD1 Q_reg(.E (CLK), .D (D), .Q (Q));
endmodule

module XOR(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__1617(.A1 (a), .A2 (b), .Z (x));
endmodule

module XOR_350(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__2802(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_349(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__1705(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_348(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__5122(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_347(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__8246(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_346(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__7098(.A1 (a), .A2 (b), .Z (x));
endmodule

module prbs7(clk, selmux, x4, x5, x6, x7);
  input clk, selmux;
  output x4, x5, x6, x7;
  wire clk, selmux;
  wire x4, x5, x6, x7;
  wire d1, d5, n_2, q1, q3, q5, q6, ql1;
  wire ql2, ql3, ql4, ql5, ql6, x1, x2, x3;
  NEGDFF dff1(q1, d1, clk);
  POSDFF dff3(q3, n_2, clk);
  NEGDFF_189 dff5(q5, d5, clk);
  POSDFF_233 dff6(q6, d5, clk);
  POSDLATCH dlatch1(ql1, q5, clk);
  NEGDLATCH dlatch2(ql2, q6, clk);
  POSDLATCH_255 dlatch3(ql3, q1, clk);
  NEGDLATCH_208 dlatch4(ql4, q3, clk);
  NEGDLATCH_207 dlatch5(ql5, ql3, clk);
  POSDLATCH_254 dlatch6(ql6, ql4, clk);
  XOR xor1(x1, ql5, ql6);
  XOR_350 xor2(x2, ql3, ql4);
  XOR_349 xor3(x3, ql1, ql2);
  XOR_348 xor4(n_2, x3, x7);
  XOR_347 xor6(d5, x1, x2);
  XOR_346 xor7(x7, q5, q6);
  OR2D1 g5__6131(.A1 (selmux), .A2 (n_2), .Z (d1));
endmodule

module NEGDFF_188(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
endmodule

module POSDFF_232(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LNQD1 Q1_reg(.EN (CLK), .D (D), .Q (Q1));
  LHQD1 Q2_reg(.E (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_187(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
endmodule

module POSDFF_231(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LNQD1 Q1_reg(.EN (CLK), .D (D), .Q (Q1));
  LHQD1 Q2_reg(.E (CLK), .D (Q1), .Q (Q2));
endmodule

module POSDLATCH_253(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LHQD1 Q_reg(.E (CLK), .D (D), .Q (Q));
endmodule

module NEGDLATCH_206(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LNQD1 Q_reg(.EN (CLK), .D (D), .Q (Q));
endmodule

module NEGDLATCH_205(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LNQD1 Q_reg(.EN (CLK), .D (D), .Q (Q));
endmodule

module POSDLATCH_252(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LHQD1 Q_reg(.E (CLK), .D (D), .Q (Q));
endmodule

module POSDLATCH_251(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LHQD1 Q_reg(.E (CLK), .D (D), .Q (Q));
endmodule

module NEGDLATCH_204(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LNQD1 Q_reg(.EN (CLK), .D (D), .Q (Q));
endmodule

module NEGDLATCH_203(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LNQD1 Q_reg(.EN (CLK), .D (D), .Q (Q));
endmodule

module POSDLATCH_250(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LHQD1 Q_reg(.E (CLK), .D (D), .Q (Q));
endmodule

module POSDLATCH_249(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LHQD1 Q_reg(.E (CLK), .D (D), .Q (Q));
endmodule

module NEGDLATCH_202(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LNQD1 Q_reg(.EN (CLK), .D (D), .Q (Q));
endmodule

module XOR_345(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__1881(.A1 (a), .A2 (b), .Z (x));
endmodule

module XOR_344(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__5115(.A1 (a), .A2 (b), .Z (x));
endmodule

module XOR_343(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__7482(.A1 (a), .A2 (b), .Z (x));
endmodule

module XOR_342(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__4733(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_341(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__6161(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_340(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__9315(.A1 (b), .A2 (a), .Z (x));
endmodule

module prbs9(clk, selmux, x4, x5, x6, x7);
  input clk, selmux;
  output x4, x5, x6, x7;
  wire clk, selmux;
  wire x4, x5, x6, x7;
  wire d1, d5, n_2, q1, q3, q5, q7, ql1;
  wire ql2, ql3, ql4, ql5, ql6, ql7, ql8, ql9;
  wire ql10, x1, x2, x3;
  NEGDFF_188 dff1(q1, d1, clk);
  POSDFF_232 dff3(q3, n_2, clk);
  NEGDFF_187 dff5(q5, d5, clk);
  POSDFF_231 dff7(q7, d5, clk);
  POSDLATCH_253 dlatch1(ql1, q1, clk);
  NEGDLATCH_206 dlatch2(ql2, ql1, clk);
  NEGDLATCH_205 dlatch3(ql3, q3, clk);
  POSDLATCH_252 dlatch4(ql4, ql3, clk);
  POSDLATCH_251 dlatch5(ql5, q5, clk);
  NEGDLATCH_204 dlatch6(ql6, ql5, clk);
  NEGDLATCH_203 dlatch7(ql7, q7, clk);
  POSDLATCH_250 dlatch8(ql8, ql7, clk);
  POSDLATCH_249 dlatch9(ql9, ql2, clk);
  NEGDLATCH_202 dlatch10(ql10, ql4, clk);
  XOR_345 xor1(x1, ql9, ql10);
  XOR_344 xor2(x2, ql2, ql4);
  XOR_343 xor3(x3, ql6, ql8);
  XOR_342 xor4(n_2, x3, x7);
  XOR_341 xor6(d5, x1, x2);
  XOR_340 xor7(x7, ql5, ql7);
  OR2D1 g5__9945(.A1 (selmux), .A2 (n_2), .Z (d1));
endmodule

module NEGDFF_134(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_133(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_132(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_131(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_130(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_129(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_128(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_127(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_126(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_125(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
endmodule

module XOR_296(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__2883(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_295(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__2346(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_294(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__1666(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_293(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__7410(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_292(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__6417(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_291(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__5477(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_290(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__2398(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_289(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__5107(.A1 (a), .A2 (b), .Z (x));
endmodule

module XOR_288(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__6260(.A1 (a), .A2 (b), .Z (x));
endmodule

module XOR_287(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__4319(.A1 (a), .A2 (b), .Z (x));
endmodule

module PRBS_10B(clk, selmux, OUT1, OUT2, OUT3, OUT4);
  input clk, selmux;
  output OUT1, OUT2, OUT3, OUT4;
  wire clk, selmux;
  wire OUT1, OUT2, OUT3, OUT4;
  wire [10:1] X;
  wire [10:1] Q;
  wire [10:1] D;
  NEGDFF_134 dff1(Q[1], X[1], clk);
  NEGDFF_133 dff2(Q[2], X[2], clk);
  NEGDFF_132 dff3(Q[3], X[3], clk);
  NEGDFF_131 dff4(Q[4], X[4], clk);
  NEGDFF_130 dff5(Q[5], X[5], clk);
  NEGDFF_129 dff6(Q[6], X[6], clk);
  NEGDFF_128 dff7(Q[7], X[7], clk);
  NEGDFF_127 dff8(Q[8], X[8], clk);
  NEGDFF_126 dff9(Q[9], X[9], clk);
  NEGDFF_125 dff10(OUT4, D[9], clk);
  XOR_296 xor1(X[1], Q[1], X[8]);
  XOR_295 xor2(X[2], Q[2], X[9]);
  XOR_294 xor3(X[3], Q[3], X[10]);
  XOR_293 xor4(X[4], Q[1], Q[4]);
  XOR_292 xor5(X[5], Q[2], Q[5]);
  XOR_291 xor6(X[6], Q[3], Q[6]);
  XOR_290 xor7(X[7], Q[4], Q[7]);
  XOR_289 xor8(X[8], Q[5], Q[8]);
  XOR_288 xor9(X[9], Q[6], Q[9]);
  XOR_287 xor10(X[10], Q[7], OUT4);
  OR2D1 g5__8428(.A1 (selmux), .A2 (X[10]), .Z (D[9]));
endmodule

module NEGDFF_186(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
endmodule

module NEGDFF_185(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_184(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module POSDFF_230(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LNQD1 Q1_reg(.EN (CLK), .D (D), .Q (Q1));
  LHQD1 Q2_reg(.E (CLK), .D (Q1), .Q (Q2));
endmodule

module POSDFF_229(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q2_reg(.E (CLK), .D (Q1), .Q (Q2));
  LNQD1 Q1_reg(.EN (CLK), .D (D), .Q (Q1));
endmodule

module POSDFF_228(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q2_reg(.E (CLK), .D (Q1), .Q (Q2));
  LNQD1 Q1_reg(.EN (CLK), .D (D), .Q (Q1));
endmodule

module NEGDFF_183(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
endmodule

module NEGDFF_182(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_181(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
endmodule

module POSDFF_227(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LNQD1 Q1_reg(.EN (CLK), .D (D), .Q (Q1));
  LHQD1 Q2_reg(.E (CLK), .D (Q1), .Q (Q2));
endmodule

module POSDFF_226(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q2_reg(.E (CLK), .D (Q1), .Q (Q2));
  LNQD1 Q1_reg(.EN (CLK), .D (D), .Q (Q1));
endmodule

module POSDFF_225(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LNQD1 Q1_reg(.EN (CLK), .D (D), .Q (Q1));
  LHQD1 Q2_reg(.E (CLK), .D (Q1), .Q (Q2));
endmodule

module POSDLATCH_248(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LHQD1 Q_reg(.E (CLK), .D (D), .Q (Q));
endmodule

module NEGDLATCH_201(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LNQD1 Q_reg(.EN (CLK), .D (D), .Q (Q));
endmodule

module POSDLATCH_247(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LHQD1 Q_reg(.E (CLK), .D (D), .Q (Q));
endmodule

module NEGDLATCH_200(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LNQD1 Q_reg(.EN (CLK), .D (D), .Q (Q));
endmodule

module NEGDLATCH_199(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LNQD1 Q_reg(.EN (CLK), .D (D), .Q (Q));
endmodule

module POSDLATCH_246(Q, D, CLK);
  input D, CLK;
  output Q;
  wire D, CLK;
  wire Q;
  LHQD1 Q_reg(.E (CLK), .D (D), .Q (Q));
endmodule

module XOR_339(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__5526(.A1 (a), .A2 (b), .Z (x));
endmodule

module XOR_338(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__6783(.A1 (a), .A2 (b), .Z (x));
endmodule

module XOR_337(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__3680(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_336(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  XOR2D0 g13__1617(.A1 (a), .A2 (b), .Z (x));
endmodule

module XOR_335(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__2802(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_334(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__1705(.A1 (b), .A2 (a), .Z (x));
endmodule

module prbs15(clk, selmux, x4, x5, x6, x7);
  input clk, selmux;
  output x4, x5, x6, x7;
  wire clk, selmux;
  wire x4, x5, x6, x7;
  wire d1, d9, n_2, q1, q2, q3, q5, q6;
  wire q7, q9, q10, q11, q12, q13, q14, ql1;
  wire ql2, ql3, ql4, ql5, ql6, x1, x2, x3;
  NEGDFF_186 dff1(q1, d1, clk);
  NEGDFF_185 dff2(q2, q1, clk);
  NEGDFF_184 dff3(q3, q2, clk);
  POSDFF_230 dff5(q5, n_2, clk);
  POSDFF_229 dff6(q6, q5, clk);
  POSDFF_228 dff7(q7, q6, clk);
  NEGDFF_183 dff9(q9, d9, clk);
  NEGDFF_182 dff10(q10, q9, clk);
  NEGDFF_181 dff11(q11, q10, clk);
  POSDFF_227 dff12(q12, d9, clk);
  POSDFF_226 dff13(q13, q12, clk);
  POSDFF_225 dff14(q14, q13, clk);
  POSDLATCH_248 dlatch1(ql1, q11, clk);
  NEGDLATCH_201 dlatch2(ql2, q14, clk);
  POSDLATCH_247 dlatch3(ql3, q3, clk);
  NEGDLATCH_200 dlatch4(ql4, ql3, clk);
  NEGDLATCH_199 dlatch5(ql5, q7, clk);
  POSDLATCH_246 dlatch6(ql6, ql5, clk);
  XOR_339 xor1(x1, ql4, ql6);
  XOR_338 xor2(x2, ql3, ql5);
  XOR_337 xor3(x3, ql1, ql2);
  XOR_336 xor4(n_2, x3, x7);
  XOR_335 xor6(d9, x1, x2);
  XOR_334 xor7(x7, q11, q14);
  OR2D1 g5__5122(.A1 (selmux), .A2 (n_2), .Z (d1));
endmodule

module NEGDFF_124(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_123(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_122(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_121(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_120(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_119(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_118(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_117(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_116(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_115(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_114(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_113(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_112(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_111(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_110(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_109(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_108(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_107(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_106(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_105(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_104(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_103(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_102(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_101(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_100(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_99(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_98(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_97(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_96(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module NEGDFF_85(Q2, D, CLK);
  input D, CLK;
  output Q2;
  wire D, CLK;
  wire Q2;
  wire Q1;
  LHQD1 Q1_reg(.E (CLK), .D (D), .Q (Q1));
  LNQD1 Q2_reg(.EN (CLK), .D (Q1), .Q (Q2));
endmodule

module MUX_6(in1, in2, sel, out);
  input in1, in2, sel;
  output out;
  wire in1, in2, sel;
  wire out;
  MUX2D0 g27__8246(.I0 (in1), .I1 (in2), .S (sel), .Z (out));
endmodule

module XOR_286(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__7098(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_285(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__6131(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_284(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__1881(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_283(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__5115(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_282(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__7482(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_281(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__4733(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_280(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__6161(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_279(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__9315(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_278(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__9945(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_277(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__2883(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_276(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__2346(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_275(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__1666(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_274(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__7410(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_273(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__6417(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_272(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__5477(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_271(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__2398(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_270(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__5107(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_269(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__6260(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_268(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__4319(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_267(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__8428(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_266(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__5526(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_265(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__6783(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_264(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__3680(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_263(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__1617(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_262(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__2802(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_261(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__1705(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_260(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__5122(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_259(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__8246(.A1 (b), .A2 (a), .Z (x));
endmodule

module XOR_258(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__7098(.A1 (a), .A2 (b), .Z (x));
endmodule

module XOR_257(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__6131(.A1 (a), .A2 (b), .Z (x));
endmodule

module XOR_256(x, a, b);
  input a, b;
  output x;
  wire a, b;
  wire x;
  CKXOR2D1 g13__1881(.A1 (a), .A2 (b), .Z (x));
endmodule

module PRBS_31B(clk, selmux, OUT1, OUT2, OUT3, OUT4);
  input clk, selmux;
  output OUT1, OUT2, OUT3, OUT4;
  wire clk, selmux;
  wire OUT1, OUT2, OUT3, OUT4;
  wire [31:1] D;
  wire [31:1] Q;
  wire [31:1] X;
  wire n_0;
  NEGDFF_124 dff1(Q[1], D[1], clk);
  NEGDFF_123 dff2(Q[2], X[2], clk);
  NEGDFF_122 dff3(Q[3], X[3], clk);
  NEGDFF_121 dff4(Q[4], X[4], clk);
  NEGDFF_120 dff5(Q[5], X[5], clk);
  NEGDFF_119 dff6(Q[6], X[6], clk);
  NEGDFF_118 dff7(Q[7], X[7], clk);
  NEGDFF_117 dff8(Q[8], X[8], clk);
  NEGDFF_116 dff9(Q[9], X[9], clk);
  NEGDFF_115 dff10(Q[10], X[10], clk);
  NEGDFF_114 dff11(Q[11], X[11], clk);
  NEGDFF_113 dff12(Q[12], X[12], clk);
  NEGDFF_112 dff13(Q[13], X[13], clk);
  NEGDFF_111 dff14(Q[14], X[14], clk);
  NEGDFF_110 dff15(Q[15], X[15], clk);
  NEGDFF_109 dff16(Q[16], X[16], clk);
  NEGDFF_108 dff17(Q[17], X[17], clk);
  NEGDFF_107 dff18(Q[18], X[18], clk);
  NEGDFF_106 dff19(Q[19], X[19], clk);
  NEGDFF_105 dff21(Q[21], X[21], clk);
  NEGDFF_104 dff22(Q[22], X[22], clk);
  NEGDFF_103 dff23(Q[23], X[23], clk);
  NEGDFF_102 dff24(Q[24], X[24], clk);
  NEGDFF_101 dff25(Q[25], X[25], clk);
  NEGDFF_100 dff26(Q[26], X[26], clk);
  NEGDFF_99 dff27(Q[27], X[27], clk);
  NEGDFF_98 dff28(Q[28], X[28], clk);
  NEGDFF_97 dff29(Q[29], X[29], clk);
  NEGDFF_96 dff30(Q[30], X[30], clk);
  NEGDFF_85 dff31(Q[31], X[31], clk);
  MUX_6 mux4(Q[31], Q[24], n_0, OUT4);
  XOR_286 xor1(X[1], Q[1], X[4]);
  XOR_285 xor2(X[2], Q[2], X[5]);
  XOR_284 xor3(X[3], Q[3], X[6]);
  XOR_283 xor4(X[4], Q[4], X[7]);
  XOR_282 xor5(X[5], Q[5], X[8]);
  XOR_281 xor6(X[6], Q[6], X[9]);
  XOR_280 xor7(X[7], Q[7], X[10]);
  XOR_279 xor8(X[8], Q[8], X[11]);
  XOR_278 xor9(X[9], Q[9], X[12]);
  XOR_277 xor10(X[10], Q[10], X[13]);
  XOR_276 xor11(X[11], Q[11], X[14]);
  XOR_275 xor12(X[12], Q[12], X[15]);
  XOR_274 xor13(X[13], Q[13], X[16]);
  XOR_273 xor14(X[14], Q[14], X[17]);
  XOR_272 xor15(X[15], Q[15], X[18]);
  XOR_271 xor16(X[16], Q[16], X[19]);
  XOR_270 xor17(X[17], Q[17], X[20]);
  XOR_269 xor18(X[18], Q[18], X[21]);
  XOR_268 xor19(X[19], Q[19], X[22]);
  XOR_267 xor20(X[20], Q[21], X[23]);
  XOR_266 xor21(X[21], Q[21], X[24]);
  XOR_265 xor22(X[22], Q[22], X[25]);
  XOR_264 xor23(X[23], Q[23], X[26]);
  XOR_263 xor24(X[24], Q[24], X[27]);
  XOR_262 xor25(X[25], Q[25], X[28]);
  XOR_261 xor26(X[26], Q[26], X[29]);
  XOR_260 xor27(X[27], Q[27], X[30]);
  XOR_259 xor28(X[28], Q[28], X[31]);
  XOR_258 xor29(X[29], Q[1], Q[29]);
  XOR_257 xor30(X[30], Q[2], Q[30]);
  XOR_256 xor31(X[31], Q[3], Q[31]);
  CKND1 g7(.I (clk), .ZN (n_0));
  OR2D1 g8__5115(.A1 (X[1]), .A2 (selmux), .Z (D[1]));
endmodule

module top_module(clk, switch, sel, sel_initial, out);
  input clk, sel_initial;
  input [3:0] switch;
  input [3:1] sel;
  output out;
  wire clk, sel_initial;
  wire [3:0] switch;
  wire [3:1] sel;
  wire out;
  wire [3:0] out_module5;
  wire [3:0] out_module6;
  wire [3:0] out_module7;
  wire [3:0] out_module4;
  wire [3:0] out_module3;
  wire [3:0] out_module0;
  wire [3:0] out_module1;
  wire [3:0] out_module8;
  wire [3:0] out_module2;
  wire [3:0] out_module9;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_15, n_16;
  wire n_17, n_19, n_22, n_103_BAR;
  CRBS crbs_7(clk, sel_initial, out_module5[0], out_module5[1],
       out_module5[2], out_module5[3]);
  CRBS_9 crbs_9(clk, sel_initial, out_module6[0], out_module6[1],
       out_module6[2], out_module6[3]);
  CRBS_15 crbs_15(clk, sel_initial, out_module7[0], out_module7[1],
       out_module7[2], out_module7[3]);
  PRBS_7_9_15 prbs7_9_15(clk, sel[1], sel[2], sel[3], sel_initial,
       out_module4[0], out_module4[1], out_module4[2], out_module4[3]);
  PRBS_7_15_22 prbs7_15_22(clk, sel[1], sel[2], sel_initial,
       out_module3[0], out_module3[1], out_module3[2], out_module3[3]);
  prbs7 prbs_7(clk, sel_initial, out_module0[0], out_module0[1],
       out_module0[2], out_module0[3]);
  prbs9 prbs_9(clk, sel_initial, out_module1[0], out_module1[1],
       out_module1[2], out_module1[3]);
  PRBS_10B prbs_10bit(clk, sel_initial, out_module8[0], out_module8[1],
       out_module8[2], out_module8[3]);
  prbs15 prbs_15(clk, sel_initial, out_module2[0], out_module2[1],
       out_module2[2], out_module2[3]);
  PRBS_31B prbs_31bit(clk, sel_initial, out_module9[0], out_module9[1],
       out_module9[2], out_module9[3]);
  OAI21D1 g202__7482(.A1 (n_12), .A2 (switch[3]), .B (n_13), .ZN (out));
  AOI21D1 g203__4733(.A1 (n_10), .A2 (switch[0]), .B (n_11), .ZN
       (n_12));
  AOI21D1 g204__6161(.A1 (n_22), .A2 (n_9), .B (switch[0]), .ZN (n_11));
  ND3D1 g205__9315(.A1 (n_103_BAR), .A2 (n_19), .A3 (n_16), .ZN (n_10));
  INR2D0 g206__9945(.A1 (n_17), .B1 (n_15), .ZN (n_9));
  ND2D1 g314__2883(.A1 (n_8), .A2 (switch[3]), .ZN (n_13));
  MUX2ND0 g315__2346(.I0 (n_6), .I1 (n_7), .S (switch[0]), .ZN (n_8));
  AOI221D0 g316__1666(.A1 (n_0), .A2 (out_module4[1]), .B1 (n_2), .B2
       (out_module4[3]), .C (n_5), .ZN (n_7));
  AOI221D0 g317__7410(.A1 (n_1), .A2 (out_module3[0]), .B1 (n_2), .B2
       (out_module4[2]), .C (n_4), .ZN (n_6));
  AO22D0 g318__6417(.A1 (n_1), .A2 (out_module3[1]), .B1
       (out_module3[3]), .B2 (n_3), .Z (n_5));
  AO22D0 g319__5477(.A1 (n_1), .A2 (out_module0[3]), .B1
       (out_module8[3]), .B2 (n_2), .Z (n_15));
  AOI22D1 g320__2398(.A1 (n_0), .A2 (out_module7[3]), .B1 (n_2), .B2
       (out_module9[3]), .ZN (n_103_BAR));
  AO22D0 g321__5107(.A1 (n_0), .A2 (out_module4[0]), .B1
       (out_module3[2]), .B2 (n_3), .Z (n_4));
  CKND2D1 g322__6260(.A1 (n_3), .A2 (out_module2[3]), .ZN (n_17));
  CKND2D1 g323__4319(.A1 (n_1), .A2 (out_module1[3]), .ZN (n_16));
  ND2D1 g324__8428(.A1 (n_0), .A2 (out_module6[3]), .ZN (n_22));
  ND2D1 g325__5526(.A1 (n_3), .A2 (out_module5[3]), .ZN (n_19));
  INR2D1 g326__6783(.A1 (switch[1]), .B1 (switch[2]), .ZN (n_3));
  AN2XD1 g327__3680(.A1 (switch[2]), .A2 (switch[1]), .Z (n_2));
  NR2D1 g328__1617(.A1 (switch[2]), .A2 (switch[1]), .ZN (n_1));
  INR2D1 g329__2802(.A1 (switch[2]), .B1 (switch[1]), .ZN (n_0));
endmodule

